
/*
  program summary
  Keagan rieder
  Title: Code Scape
  
  summary:The purpose of the sketch generated by this program is to generated a city scape, and with use of colors represnt differnt state of the city
  at differnt day.
  
  ###########################################################################################
    controls 
    begin saving frames : s
    screenshot          : a
  
    switching times
    switch to day       : d
    switch to day       : n
  
    spawning things
    spawn car           : v
    unspawn car         : b
    spawn cloud         : c
    unspawn car         : x
  
    other controls
    turn power on       : p
    turn power off      : o
  
  ###########################################################################################
*/

/* 
###########################################################################################
  File Summary
  >> conatins the programs setup functions
  >> conatins the programs draw functions (main program loop)
  >> varibles which are used throughout the porgram 
  and aren't just spefcic to this file
###########################################################################################
*/

//global Varibles
int inputDelay = 0;
int scene = 0;
int horizenLine;
int saveDelay = 0;
boolean isDay = false;
boolean drawSun = false;

//Program Setup
void setup(){
  frameRate(30);
  size(1920,1080);
  horizenLine = height-300;
  //initalizing background
  InitalizeBackGround();
}

//program draw function
void draw(){
  //repeatly red drawing background
  DrawBackGround();
  //checking for interaction
  CheckForInteraction();
  //svaing after delay
  if(saveDelay >= 15){
    SaveCurrentFrame();
    saveDelay =0;
  }
  saveDelay++;
}
